@startuml

participant 클라이언트 as c
participant 주문모듈 as o
participant 결제모듈 as p
participant PG사 as pg

autonumber 1 "(0)"
c -> o : 주문 생성 및 PENDING 상태
activate o
c <-- o
deactivate o

c -> pg : 결제 요청
activate pg
c <-- pg
deactivate pg

c -> o : 결제 검증 요청
activate o
alt 유효성 검사 실패 case
o -> o : merchantID 유효성
end
o -> p : 결제 취소 이벤트
activate p
p -> pg : 결제 취소 요청
activate pg
p <-- pg:
deactivate pg
o <-- p:
deactivate p
c <-- o : 결제 실패 상태 응답

deactivate o


@enduml
